version: "3.9"

volumes:
  mysite_postgres:

networks:
  mysite:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: "postgres:13"
    volumes:
      - mysite_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    networks:
      - mysite
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

