apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysite-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AlexUngerDev/mysite.git
    targetRevision: HEAD
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: mysite

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true