apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        bb: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - name: postgres
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 0.3Gi