# Generated by Django 3.2.8 on 2021-10-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_comleted_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desciption',
            new_name='task_description',
        ),
    ]
